apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "todo-app.fullname" . }}-config
  labels:
    app: {{ include "todo-app.name" . }}
data:
  api-url: {{ .Values.config.backend.apiUrl | quote }}
  next-public-api-url: {{ .Values.config.frontend.nextPublicApiUrl | quote }}
